// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hotel.proto

package hotel

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	proto1 "github.com/ziyoubiancheng/lesson_gomicro/lesson_3_go_micro_booking/srv/profile/proto"
	proto2 "github.com/ziyoubiancheng/lesson_gomicro/lesson_3_go_micro_booking/srv/rate/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Request struct {
	InDate               string   `protobuf:"bytes,1,opt,name=inDate,proto3" json:"inDate,omitempty"`
	OutDate              string   `protobuf:"bytes,2,opt,name=outDate,proto3" json:"outDate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_169099f938a8a4b0, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetInDate() string {
	if m != nil {
		return m.InDate
	}
	return ""
}

func (m *Request) GetOutDate() string {
	if m != nil {
		return m.OutDate
	}
	return ""
}

type Response struct {
	Hotels               []*proto1.Hotel    `protobuf:"bytes,1,rep,name=hotels,proto3" json:"hotels,omitempty"`
	RatePlans            []*proto2.RatePlan `protobuf:"bytes,2,rep,name=ratePlans,proto3" json:"ratePlans,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_169099f938a8a4b0, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetHotels() []*proto1.Hotel {
	if m != nil {
		return m.Hotels
	}
	return nil
}

func (m *Response) GetRatePlans() []*proto2.RatePlan {
	if m != nil {
		return m.RatePlans
	}
	return nil
}

func init() {
	proto.RegisterType((*Request)(nil), "hotel.Request")
	proto.RegisterType((*Response)(nil), "hotel.Response")
}

func init() { proto.RegisterFile("hotel.proto", fileDescriptor_169099f938a8a4b0) }

var fileDescriptor_169099f938a8a4b0 = []byte{
	// 257 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x91, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xed, 0x4a, 0xbb, 0x6e, 0x16, 0x56, 0xc8, 0x41, 0x4a, 0x4f, 0x4b, 0x0f, 0xb2, 0x88,
	0x34, 0xb0, 0x3d, 0x7a, 0xf5, 0xe0, 0x51, 0x72, 0x16, 0x6a, 0x53, 0x62, 0x1a, 0x6c, 0x33, 0x35,
	0x49, 0x05, 0xfd, 0xf5, 0xd2, 0x69, 0xa2, 0x7f, 0xc0, 0x5b, 0xbe, 0x79, 0x93, 0x79, 0x6f, 0x12,
	0xb2, 0xef, 0xc1, 0xcb, 0xa1, 0x9a, 0x2c, 0x78, 0xa0, 0x29, 0x42, 0x21, 0x94, 0xf6, 0xfd, 0x2c,
	0xaa, 0x0e, 0x46, 0xf6, 0xad, 0xbf, 0x60, 0x16, 0xba, 0x35, 0x5d, 0x2f, 0x8d, 0x62, 0x83, 0x74,
	0x0e, 0x4c, 0xa3, 0x60, 0xd4, 0x9d, 0x85, 0x88, 0x75, 0xa3, 0xa0, 0xc1, 0x4a, 0x23, 0x00, 0xde,
	0xb5, 0x51, 0xcc, 0xd9, 0x4f, 0x36, 0x59, 0x78, 0xd3, 0x83, 0x64, 0x38, 0x3c, 0xd2, 0x6a, 0x55,
	0xbc, 0xfc, 0x93, 0x87, 0x6d, 0x7d, 0x34, 0x58, 0x8e, 0xeb, 0xf4, 0xf2, 0x81, 0x6c, 0xb9, 0xfc,
	0x98, 0xa5, 0xf3, 0xf4, 0x86, 0x64, 0xda, 0x3c, 0xb6, 0x5e, 0xe6, 0xc9, 0x31, 0x39, 0xed, 0x78,
	0x20, 0x9a, 0x93, 0x2d, 0xcc, 0x1e, 0x85, 0x0d, 0x0a, 0x11, 0xcb, 0x57, 0x72, 0xc5, 0xa5, 0x9b,
	0xc0, 0x38, 0x49, 0x6f, 0x49, 0x86, 0x6f, 0xe2, 0xf2, 0xe4, 0x78, 0x79, 0xda, 0x9f, 0x0f, 0x55,
	0x5c, 0xe3, 0x69, 0x29, 0xf3, 0xa0, 0xd2, 0x7b, 0xb2, 0x5b, 0xec, 0x9f, 0x87, 0xd6, 0xb8, 0x7c,
	0x13, 0x5a, 0x31, 0x10, 0x0f, 0x65, 0xfe, 0xd7, 0x70, 0xae, 0x49, 0x8a, 0xd7, 0xe9, 0x1d, 0x49,
	0x17, 0xdd, 0xd1, 0x43, 0xb5, 0xfe, 0x43, 0x48, 0x5d, 0x5c, 0xff, 0xf2, 0x1a, 0xa4, 0xbc, 0x10,
	0x19, 0xae, 0x56, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x92, 0x3f, 0x32, 0x28, 0xb2, 0x01, 0x00,
	0x00,
}
